AWSTemplateFormatVersion: '2010-09-09'
Description:  >
  Deploys ACM certificatate, IAM group/policy/user, S3 buckets and CloudFront
  distribution. Certificate needs to be requested in us-east-1 region in order
  to work CloudFront distribution.

Parameters:
  DomainName:
    Description: 'name of domain pointing to static website, e.g domain.com'
    Type: String
  GroupName:
    Description: 'username with admin level access to S3 buckets'
    Type: String
  Region:
    Description: 'default region name'
    Type: String

Resources:
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub 'www.${DomainName}'

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html

  S3BucketLog:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DomainName}-log'
    DependsOn:
      - S3Bucket

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: ReadAccess
            Action:
              - 's3:GetObject'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Principal: '*'

  IAMUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName

  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${GroupName}-Admin'
      Groups:
        - !Ref IAMUserGroup

  IAMUserGroupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref GroupName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: FullAdminS3BucketStaticSite
            Effect: "Allow"
            Action: "*"
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3BucketLog}/*'
              - !Sub 'arn:aws:s3:::${S3BucketLog}'
      Groups:
        - Ref: IAMUserGroup

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Comment: !Sub 'CDN for S3-backed website: ${DomainName}'
        # CustomErrorResponses:
        #   - ErrorCode: '404'
        #     ResponsePagePath: "/404"
        #     ResponseCode: '200'
        #     ErrorCachingMinTTL: '30'
        DefaultCacheBehavior:
          AllowedMethods: # other methods: DELETE,OPTIONS,PATCH,POST,PUT
            - GET
            - HEAD
          Compress: 'true'
          DefaultTTL: 1800
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: 'false'
          MinTTL: 0
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: index.html
        Enabled: 'true'
        HttpVersion: http2
        Logging:
          IncludeCookies: 'false'
          Bucket: !Sub '${DomainName}-log.s3.amazonaws.com'
          Prefix: logs/
        Origins:
          - CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
            DomainName: !Select [2, !Split ['/', !GetAtt 'S3Bucket.WebsiteURL']]
            Id: S3Origin
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: 'sni-only'
    DependsOn:
      - S3Bucket
      - S3BucketLog

  Route53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: 'Zone apex alias targeted to CloudFront distribution'
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # AWS CloudFront magic ID
            DNSName: !GetAtt [CloudFrontDistribution, DomainName]
        - Name: !Sub 'www.${DomainName}'
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [CloudFrontDistribution, DomainName]
