AWSTemplateFormatVersion: '2010-09-09'
Description:  >
  Deploys ACM certificate for encrypted access to S3 based static website. To
  use certificate with CloudFront, it needs to be requested from the us-east-1
  region. Certs in this region that are associated with a CloudFront
  distribution are distributed to all the geographic locations configured for
  that distribution
Parameters:
  DomainName:
    Description: 'name of domain pointing to static website, e.g domain.com'
    Type: String
  GroupName:
    Description: 'username with admin level access to S3 buckets'
    Type: String

Resources:
  Certificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Sub '*.${DomainName}'
