AWSTemplateFormatVersion: '2010-09-09'
Description:  >
  Deploys a CodeCommit repository and CodePipeline pipeline.

Parameters:
  DomainName:
    Description: 'name of domain pointing to static website, e.g domain.com'
    Type: String
  GroupName:
    Description: 'username with admin level access to S3 buckets'
    Type: String
  Region:
    Description: 'default region name'
    Type: String

Resources:
  BlogRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref DomainName
      RepositoryDescription: !Sub 'Repo for static website: ${DomainName}'
